global:
  scrape_interval:     5s 
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'microservice'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.postgres-network.backend-service:8080']